In [16]:
import numpy as np
import pandas as pd

In [ ]:
#Question 1
"""
(a) Create a 1D NumPy array with values 1 to 20. 
(b) Extract all prime numbers from it. 
(c) Compute the mean and variance of the extracted primes.
"""
import numpy as np

a = np.arange(1, 21)
primes = np.array([x for x in a if all(x % i for i in range(2, int(x**0.5)+1)) and x>1])
mean_val, var_val = primes.mean(), primes.var()
primes, mean_val, var_val


(array([ 2,  3,  5,  7, 11, 13, 17, 19]), 9.625, 35.734375)

In [18]:
#Question 2
"""
(a) Create a 4×4 NumPy array with numbers 1 to 16. 
(b) Extract the 2×2 bottom-left sub-matrix. 
(c) Compute the determinant of the sub-matrix. 
"""

import numpy as np 
seq_arr = np.arange(1, 17).reshape(4, 4)
sub_matrix = seq_arr[2:4, 0:2]
det_val = np.linalg.det(sub_matrix)

In [19]:
#Question 3
"""Create a DataFrame with 5 students and marks in 3 subjects. 
(b) Add a column for total and average marks. 
(c) Identify the topper and print their name with average."""

df = pd.DataFrame({
    'Name': ['Alice','Bob','Charlie','David','Eva'],
    'Math':[85,76,90,65,92],
    'Physics':[88,69,95,70,89],
    'Chemistry':[91,72,85,68,94]
})
df['Total'] = df[['Math','Physics','Chemistry']].sum(axis=1)
df['Average'] = df[['Math','Physics','Chemistry']].mean(axis=1)
topper = df.loc[df['Average'].idxmax()]
df, topper['Name'], topper['Average']


(      Name  Math  Physics  Chemistry  Total    Average
 0    Alice    85       88         91    264  88.000000
 1      Bob    76       69         72    217  72.333333
 2  Charlie    90       95         85    270  90.000000
 3    David    65       70         68    203  67.666667
 4      Eva    92       89         94    275  91.666667,
 'Eva',
 91.66666666666667)

In [20]:
#Question 4
"""(a) Simulate 1000 coin tosses using NumPy (1=Head, 0=Tail). 
(b) Count frequency of heads and tails. 
(c) Estimate probability of heads. Is it close to 0.5? Why/Why not?"""

np.random.seed(42)
tosses = np.random.randint(0, 2, 1000)
heads = tosses.sum()
tails = 1000 - heads
prob_heads = heads / 1000
heads, tails, prob_heads

(510, 490, 0.51)

In [21]:
#Question 5
"""(a) Create a DataFrame of employees with columns: ID, Name, Salary. 
(b) Add a Bonus column = 10% of Salary. 
(c) Display employees with salary above average."""
df = pd.DataFrame({
    'ID':[101,102,103,104,105],
    'Name':['Alice','Bob','Charlie','David','Eva'],
    'Salary':[50000,60000,55000,45000,70000]
})
df['Bonus'] = df['Salary']*0.1
above_avg = df[df['Salary'] > df['Salary'].mean()]
df, above_avg

(    ID     Name  Salary   Bonus
 0  101    Alice   50000  5000.0
 1  102      Bob   60000  6000.0
 2  103  Charlie   55000  5500.0
 3  104    David   45000  4500.0
 4  105      Eva   70000  7000.0,
     ID Name  Salary   Bonus
 1  102  Bob   60000  6000.0
 4  105  Eva   70000  7000.0)

In [22]:
#Question 6
"""(a) Create a 3×3 NumPy array with values 1 to 9. 
(b) Find its transpose and inverse. 
(c) Verify that A × A⁻¹ ≈ I. """

A = np.array([[1,2,3],[0,1,4],[5,6,0]])
A_T = A.T
A_inv = np.linalg.inv(A)
I_approx = A @ A_inv
A, A_T, A_inv, I_approx

(array([[1, 2, 3],
        [0, 1, 4],
        [5, 6, 0]]),
 array([[1, 0, 5],
        [2, 1, 6],
        [3, 4, 0]]),
 array([[-24.,  18.,   5.],
        [ 20., -15.,  -4.],
        [ -5.,   4.,   1.]]),
 array([[ 1.00000000e+00, -1.77635684e-15, -4.44089210e-16],
        [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]]))

In [23]:
#Question 7
"""(a) Generate random daily temperatures (30 values, range 20–40°C). 
(b) Find the hottest and coldest day. 
(c) Compute mean, median, and standard deviation of temperatures. 
"""
np.random.seed(42)
temps = np.random.uniform(20, 40, 30)
hottest_day, coldest_day = temps.argmax()+1, temps.argmin()+1
mean_temp, median_temp, std_temp = temps.mean(), np.median(temps), temps.std()
temps, hottest_day, temps.max(), coldest_day, temps.min(), mean_temp, median_temp, std_temp


(array([27.49080238, 39.01428613, 34.63987884, 31.97316968, 23.12037281,
        23.11989041, 21.16167224, 37.32352292, 32.02230023, 34.16145156,
        20.41168989, 39.39819704, 36.64885282, 24.24678221, 23.63649934,
        23.6680902 , 26.08484486, 30.49512863, 28.63890037, 25.8245828 ,
        32.23705789, 22.78987721, 25.84289297, 27.32723687, 29.12139968,
        35.70351923, 23.99347564, 30.28468877, 31.84829138, 20.92900825]),
 12,
 39.39819704323989,
 11,
 20.411689885916047,
 28.771945441948734,
 28.064851374894783,
 5.5532166060223425)

In [24]:
#Question 8
"""(a) Create a Pandas Series of marks for 8 students. 
(b) Replace all marks below 40 with “Fail”. 
(c) Count how many students passed."""

marks = pd.Series([55,72,38,90,45,30,65,80],index=[f'Student{i+1}' for i in range(8)])
marks_mod = marks.apply(lambda x: 'Fail' if x<40 else x)
num_passed = (marks_mod != 'Fail').sum()
marks_mod, num_passed


(Student1      55
 Student2      72
 Student3    Fail
 Student4      90
 Student5      45
 Student6    Fail
 Student7      65
 Student8      80
 dtype: object,
 6)

In [25]:
#Question 9
""" (a) Generate 500 random integers between 1 and 6 (simulate dice rolls). 
(b) Count how many times each face appears. 
(c) Compute relative frequencies and compare with theoretical 1/6. """

np.random.seed(42)
rolls = np.random.randint(1,7,500)
counts = np.bincount(rolls)[1:]
rel_freq = counts / 500
rolls[:20], counts, rel_freq, 1/6

(array([4, 5, 3, 5, 5, 2, 3, 3, 3, 5, 4, 3, 6, 5, 2, 4, 6, 6, 2, 4]),
 array([90, 75, 77, 97, 75, 86], dtype=int64),
 array([0.18 , 0.15 , 0.154, 0.194, 0.15 , 0.172]),
 0.16666666666666666)

In [26]:
#Question 10
"""(a) Create a DataFrame with 6 products (Name, Quantity, Price). 
(b) Add a column “Total = Quantity × Price”. 
(c) Find which product generated maximum sales revenue."""

df = pd.DataFrame({
    'Name':['Laptop','Mouse','Keyboard','Monitor','Printer','Speaker'],
    'Quantity':[5,20,15,7,3,10],
    'Price':[50000,800,1500,12000,7000,2000]
})
df['Total'] = df['Quantity']*df['Price']
max_product = df.loc[df['Total'].idxmax()]
df, max_product['Name'], max_product['Total']


(       Name  Quantity  Price   Total
 0    Laptop         5  50000  250000
 1     Mouse        20    800   16000
 2  Keyboard        15   1500   22500
 3   Monitor         7  12000   84000
 4   Printer         3   7000   21000
 5   Speaker        10   2000   20000,
 'Laptop',
 250000)

In [27]:
#Question 11
""" (a) Create a DataFrame with some missing values (NaN). 
(b) Fill missing values with column mean. 
(c) Drop rows where more than 1 value is missing. """

df = pd.DataFrame({
    'A':[1,2,np.nan,4,5],
    'B':[5,np.nan,np.nan,8,10],
    'C':[10,20,30,np.nan,50]
})
df_filled = df.fillna(df.mean())
df_dropped = df.dropna(thresh=df.shape[1]-1)
df, df_filled, df_dropped

(     A     B     C
 0  1.0   5.0  10.0
 1  2.0   NaN  20.0
 2  NaN   NaN  30.0
 3  4.0   8.0   NaN
 4  5.0  10.0  50.0,
      A          B     C
 0  1.0   5.000000  10.0
 1  2.0   7.666667  20.0
 2  3.0   7.666667  30.0
 3  4.0   8.000000  27.5
 4  5.0  10.000000  50.0,
      A     B     C
 0  1.0   5.0  10.0
 1  2.0   NaN  20.0
 3  4.0   8.0   NaN
 4  5.0  10.0  50.0)

In [28]:
#Question 12
"""(a) Create a NumPy array with integers from 1 to 30. 
(b) Reshape it into a 5×6 matrix. 
(c) Extract all even numbers from the matrix and compute their average."""

import numpy as np
arr = np.arange(1, 31)
matrix = arr.reshape(5, 6)
even_numbers = matrix[matrix % 2 == 0]
average_even = even_numbers.mean()
even_numbers, average_even


(array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]), 16.0)

In [29]:
#Question 13
""" (a) Create a DataFrame of 6 students with columns: Name, Age, Marks. 
(b) Select only students who scored above the overall average marks. 
(c) Display names of students younger than 20 whose marks are above 60."""

import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank'],
    'Age': [19, 21, 18, 22, 20, 17],
    'Marks': [75, 65, 80, 55, 90, 62]
}
df = pd.DataFrame(data)
average_marks = df['Marks'].mean()
above_average = df[df['Marks'] > average_marks]
young_high_scorers = df[(df['Age'] < 20) & (df['Marks'] > 60)]['Name']
above_average, young_high_scorers


(      Name  Age  Marks
 0    Alice   19     75
 2  Charlie   18     80
 4      Eva   20     90,
 0      Alice
 2    Charlie
 5      Frank
 Name: Name, dtype: object)

In [30]:
#Question 14
"""(a) Create a Pandas DataFrame with 5 employees having columns: Name, Tasks_Completed, 
Hours_Worked. 
(b) Add a new column Efficiency = Tasks_Completed / Hours_Worked. 
(c) Identify the employee with the highest efficiency and print their name and value. """

import pandas as pd
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Tasks_Completed': [50, 40, 60, 30, 70],
    'Hours_Worked': [10, 8, 12, 6, 14]
}
df = pd.DataFrame(data)
df['Efficiency'] = df['Tasks_Completed'] / df['Hours_Worked']
top_employee = df.loc[df['Efficiency'].idxmax(), ['Name', 'Efficiency']]

top_employee


Name          Alice
Efficiency      5.0
Name: 0, dtype: object