
---

## 📌 Cell 1: Install Required Libraries

```python
pip install numpy
pip install pandas
!pip install matplotlib
```

---

## 📌 Cell 2: Input and Data Type

```python
num = input("enter a number")
print(type(num))
```

---

## 📌 Cell 3: Integer Type

```python
num = 5
type(num)
```

---

## 📌 Cell 4: Float Type

```python
num = 7.9
type(num)
```

---

## 📌 Cell 5: Complex Number

```python
num = -3 + 7.2j
type(num)
```

---

## 📌 Cell 6: Boolean Type

```python
var1 = True
type(var1)
```

---

## 📌 Cell 7: Arithmetic Operations

```python
a = 10
b = 3

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponentiation:", a ** b)
```

---

## 📌 Cell 8: Comparison Operations

```python
x = 5
y = 8

print("Equal:", x == y)
print("Not Equal:", x != y)
print("Greater than:", x > y)
print("Less than:", x < y)
print("Greater than or equal:", x >= y)
print("Less than or equal:", x <= y)
```

---

## 📌 Cell 9: Logical Operations

```python
p = True
q = False

print("AND:", p and q)
print("OR:", p or q)
print("NOT p:", not p)
print("NOT q:", not q)
```

---

## 📌 Cell 10: String Operations

```python
str1 = "Hello"
str2 = "World"

print("Concatenation:", str1 + " " + str2)
print("Repetition:", str1 * 3)
print("Length:", len(str1))
print("Uppercase:", str1.upper())
print("Lowercase:", str1.lower())
print("Contains 'ell':", "ell" in str1)
```

---

## 📌 Cell 11: String Type Check

```python
str1 = 'Hello Friend'
str2 = "452"

print(type(str1))
print(type(str2))
```

---

## 📌 Cell 12: List Example

```python
list1 = [5, 3.4, "New Delhi", "20C", 45]
print(list1)
type(list1)
```

---

## 📌 Cell 13: List Slicing and Methods

```python
numbers = [0,1,2,3,4,5,6,7,8,9]

print("Original:", numbers)
print("First 3:", numbers[:3])
print("Last 3:", numbers[-3:])
print("Middle:", numbers[3:7])
print("Every second:", numbers[::2])
print("Reverse:", numbers[::-1])
print("Length:", len(numbers))
print("Sum:", sum(numbers))
print("Max:", max(numbers))
print("Min:", min(numbers))
```

---

## 📌 Cell 14: Tuple Example

```python
tuple1 = (10, 20, "Apple", 3.4, 'a')
print(tuple1)
type(tuple1)
```

---

## 📌 Cell 15: Dictionary Example

```python
dict1 = {'Fruit':'Apple', 'Climate':'Cold', 'Price(kg)':120}
print(dict1)
print(dict1['Price(kg)'])
```

---

## 📌 Cell 16: Dictionary with Integer Keys

```python
dict2 = {1:'Akash', 2:'Amit', 3:'Rohit'}
print(dict2)
print(dict2[3])
```

---

## 📌 Cell 17: For Loop (Squares)

```python
for i in range(1,4):
    print(i*i)
```

---

## 📌 Cell 18: For Loop with List

```python
fruits = ["apple", "banana", "cherry"]

for i in fruits:
    print(i)
```

---

## 📌 Cell 19: For Loop with Step

```python
for i in range(0,4,2):
    print(i)
```

---

## 📌 Cell 20: While Loop

```python
i = 0
while i < 5:
    print(i*i)
    i = i + 1
```

---

## 📌 Cell 21: If–Else Statement

```python
i = -5
if i < 0:
    print(i*i)
else:
    print(i)
```

---

## 📌 Cell 22: Factorial Function

```python
def factorial(n):
    fact = 1
    for i in range(1, n+1):
        fact = fact * i
    return fact

factorial(6)
```

---

## 📌 Cell 23: Import NumPy

```python
import numpy as np
```

---

## 📌 Cell 24: NumPy Array

```python
x = np.array([1, 2, 3])
print(x)
type(x)
```

---

## 📌 Cell 25: Mean, Median, Standard Deviation

```python
arr = np.array([10, 20, 30, 40])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
```

---

## 📌 Cell 26: Array Shape and Size

```python
data = np.array([[1,4.7,3], ['Hello',5,'ITER']])

print(data)
print(data.ndim)
print(data.shape)
print(data.size)
```

---

## 📌 Cell 27: Zeros, Ones, Empty

```python
np.zeros(10)
np.ones(10)
np.zeros((2,3))
np.empty(2)
```

---

## 📌 Cell 28: arange and linspace

```python
np.arange(6)
np.arange(10, 20, 5)
np.linspace(10, 20, 5)
```

---

## 📌 Cell 29: full, eye, identity

```python
np.full(10, 5)
np.full((2,3), 5)
np.eye(4)
np.identity(4)
np.eye(4, k=-1)
```

---

## 📌 Cell 30: Data Types and astype

```python
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr3 = np.array([1,2,3])
arr4 = np.array(['1','2','3'])
arr5 = np.array([['1111','2222','3333'],['1','2','3']])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)
```

---

## 📌 Cell 31: Type Conversion

```python
arr1 = np.array([1,2,3,4,5,6])
arr1 = arr1.astype(np.float64)
print(arr1, arr1.dtype)
```

---

## 📌 Cell 32: NumPy Arithmetic Operations

```python
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,6,7],[9,3,2]])

arr1 + arr2
```

---

## 📌 Cell 33: More NumPy Operations

```python
arr1 * arr2
7 * arr1
arr1 ** 2
arr1 > arr2
7 / arr2
```

---



In [2]:
num = input("enter a number")
print(type(num))

<class 'str'>


In [3]:
num = 5
type(num)


int

In [4]:
num = 7.9
type(num)


float

In [5]:
num = -3 + 7.2j
type(num)


complex

In [6]:
var1 = True
type(var1)


bool

In [7]:
a = 10
b = 3

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)
print("Floor Division:", a // b)
print("Modulus:", a % b)
print("Exponentiation:", a ** b)


Addition: 13
Subtraction: 7
Multiplication: 30
Division: 3.3333333333333335
Floor Division: 3
Modulus: 1
Exponentiation: 1000


In [8]:
x = 5
y = 8

print("Equal:", x == y)
print("Not Equal:", x != y)
print("Greater than:", x > y)
print("Less than:", x < y)
print("Greater than or equal:", x >= y)
print("Less than or equal:", x <= y)


Equal: False
Not Equal: True
Greater than: False
Less than: True
Greater than or equal: False
Less than or equal: True


In [9]:
p = True
q = False

print("AND:", p and q)
print("OR:", p or q)
print("NOT p:", not p)
print("NOT q:", not q)


AND: False
OR: True
NOT p: False
NOT q: True


In [10]:
str1 = "Hello"
str2 = "World"

print("Concatenation:", str1 + " " + str2)
print("Repetition:", str1 * 3)
print("Length:", len(str1))
print("Uppercase:", str1.upper())
print("Lowercase:", str1.lower())
print("Contains 'ell':", "ell" in str1)


Concatenation: Hello World
Repetition: HelloHelloHello
Length: 5
Uppercase: HELLO
Lowercase: hello
Contains 'ell': True


In [11]:
str1 = 'Hello Friend'
str2 = "452"

print(type(str1))
print(type(str2))


<class 'str'>
<class 'str'>


In [12]:
list1 = [5, 3.4, "New Delhi", "20C", 45]
print(list1)
type(list1)


[5, 3.4, 'New Delhi', '20C', 45]


list

In [13]:
numbers = [0,1,2,3,4,5,6,7,8,9]

print("Original:", numbers)
print("First 3:", numbers[:3])
print("Last 3:", numbers[-3:])
print("Middle:", numbers[3:7])
print("Every second:", numbers[::2])
print("Reverse:", numbers[::-1])
print("Length:", len(numbers))
print("Sum:", sum(numbers))
print("Max:", max(numbers))
print("Min:", min(numbers))


Original: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
First 3: [0, 1, 2]
Last 3: [7, 8, 9]
Middle: [3, 4, 5, 6]
Every second: [0, 2, 4, 6, 8]
Reverse: [9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
Length: 10
Sum: 45
Max: 9
Min: 0


In [14]:
tuple1 = (10, 20, "Apple", 3.4, 'a')
print(tuple1)
type(tuple1)


(10, 20, 'Apple', 3.4, 'a')


tuple

In [15]:
dict2 = {1:'Akash', 2:'Amit', 3:'Rohit'}
print(dict2)
print(dict2[3])


{1: 'Akash', 2: 'Amit', 3: 'Rohit'}
Rohit


In [16]:
for i in range(1,4):
    print(i*i)


1
4
9


In [17]:
fruits = ["apple", "banana", "cherry"]

for i in fruits:
    print(i)


apple
banana
cherry


In [18]:
for i in range(0,4,2):
    print(i)


0
2


In [19]:
i = 0
while i < 5:
    print(i*i)
    i = i + 1


0
1
4
9
16


In [20]:
i = -5
if i < 0:
    print(i*i)
else:
    print(i)


25


In [21]:
def factorial(n):
    fact = 1
    for i in range(1, n+1):
        fact = fact * i
    return fact

factorial(6)


720

In [22]:
import numpy as np


In [23]:
x = np.array([1, 2, 3])
print(x)
type(x)


[1 2 3]


numpy.ndarray

In [24]:
arr = np.array([10, 20, 30, 40])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))


25.0
25.0
11.180339887498949


In [25]:
data = np.array([[1,4.7,3], ['Hello',5,'ITER']])

print(data)
print(data.ndim)
print(data.shape)
print(data.size)


[['1' '4.7' '3']
 ['Hello' '5' 'ITER']]
2
(2, 3)
6


In [26]:
np.zeros(10)
np.ones(10)
np.zeros((2,3))
np.empty(2)


array([4.24399158e-313, 8.48798317e-313])

In [27]:
np.arange(6)
np.arange(10, 20, 5)
np.linspace(10, 20, 5)


array([10. , 12.5, 15. , 17.5, 20. ])

In [28]:
np.arange(6)
np.arange(10, 20, 5)
np.linspace(10, 20, 5)


array([10. , 12.5, 15. , 17.5, 20. ])

In [29]:
np.full(10, 5)
np.full((2,3), 5)
np.eye(4)
np.identity(4)
np.eye(4, k=-1)


array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [30]:
arr1 = np.array([1,2,3], dtype=np.float64)
arr2 = np.array([1,2,3], dtype=np.int32)
arr3 = np.array([1,2,3])
arr4 = np.array(['1','2','3'])
arr5 = np.array([['1111','2222','3333'],['1','2','3']])

print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)
print(arr4.dtype)
print(arr5.dtype)


float64
int32
int32
<U1
<U4


In [31]:
arr1 = np.array([1,2,3,4,5,6])
arr1 = arr1.astype(np.float64)
print(arr1, arr1.dtype)


[1. 2. 3. 4. 5. 6.] float64


In [32]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[5,6,7],[9,3,2]])

arr1 + arr2


array([[ 6,  8, 10],
       [13,  8,  8]])

In [33]:
arr1 * arr2
7 * arr1
arr1 ** 2
arr1 > arr2
7 / arr2


array([[1.4       , 1.16666667, 1.        ],
       [0.77777778, 2.33333333, 3.5       ]])